sonar.organization=basingh47-1
sonar.projectKey=basingh47_BrainHub
sonar.projectName=BrainHub
sonar.sources=app
sonar.tests=tests
sonar.php.coverage.reportPaths=coverage.xml
sonar.exclusions=vendor/**,node_modules/**,public/build/**,storage/**,bootstrap/cache/**
